#!/usr/bin/with-contenv bash

# cleanup pid if it exists
[[ -e /config/rtdclient.pid ]] && \
	rm -rf /config/rtdclient.pid

[[ -e /data/rtdclient.pid ]] && \
	rm -rf /data/rtdclient.pid

# permissions
if [ -z "${SKIP_CHOWN}" ] || [ "${SKIP_CHOWN}" = "false" ]; then
	echo "Setting permissions"
	chown -R abc:abc \
		/app /data
else
	echo "Skipping permissions (SKIP_CHOWN is set)"
fi
